global:
  scrape_interval: 5s

scrape_configs:
  - job_name: 'app'
    scrape_interval: 5s
    static_configs:
      - targets: ['app:3000']
  - job_name: docker_stats
    static_configs:
      - targets: ['docker_stats_exporter:9487']
