version: '3'
services:
  app:
    build:
      context: ../..
      dockerfile: ../../Dockerfile
    image: nestjs-starter-perf-nest
    environment:
      - NODE_ENV=production
      - APP_ENTRY=starter
    ports:
      - '3000:3000'
    volumes:
      - ./default-config.yml:/app/resources/default-config.yml
